### ISSUE TITLE
Deploy an installable version on NPM

### ISSUE THREAD

**Issue by arturfsousa** [globocom/ScrollSpy#4]
Prepare the code to be installable and used in the browser. https://rollupjs.org/guide/en/ should  be a good option to generate the package.

**Comment by caseyWebb** [comment]
@arturfsousa for clarity, is this to convert to ES modules (for use via NPM + consumer-side bundling) and then produce output akin to the current code for consumption in the browser (no bundling required)?

**Comment by arturfsousa** [comment]
Hey @caseyWebb the ideal would be a UMD bundle, or two separated bundles:

1- CJS (node)
2- IIFE (browser) via <script>

Check this blog post for more details:

https://medium.com/@kelin2025/so-you-wanna-use-es6-modules-714f48b3a953

And ask here if you need any help.

**Comment by caseyWebb** [comment]
I'm actually really familiar with module systems and build processes. IME, the ideal dist is two builds: a UMD bundle for browser/cjs, and raw ESM for modern bundlers, with package.json->main pointing to the UMD, and package.json->module pointing to the ESM. This makes things transparently testable in node (jest, mocha, etc.) without consumers needing to transpile (while keeping `window` clean, unless just using a script tag), and still getting as close to the source when used by webpack/rollup/parcel/etc consumers, and for the few people out there using esm in the browser natively (`<script type="module">`).

If you'd be interested in TypeScript I can take this on. In that case, the typescript compiler could handle all the work as it can output any module type, and there are no third-party deps that need to be bundled alongside. Plus, automatic type declarations (.d.ts) that you don't have to worry about getting out of sync.

**Comment by arturfsousa** [comment]
Sounds really good to me. You can use typescript to archive that.

Thanks @caseyWebb
